#!/bin/bash
while IFS= read -r line
do
data='{"to":"'$line'", "data": {"body":"text message"}}'
(curl -X POST \
  https://fcm.googleapis.com/fcm/send \
  -H 'Authorization: key=token' \
  -H 'Content-Type: application/json' \
  -H 'Postman-Token: c8af5355-dbf2-4762-9b37-a6b89484cf07' \
  -H 'cache-control: no-cache' \
  -d "$data")
done < test_1.txt>result_test.txt
wc -l test_1.txt

